# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgis_wtyczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaQGISDialogBase(object):
    def setupUi(self, WtyczkaQGISDialogBase):
        WtyczkaQGISDialogBase.setObjectName("WtyczkaQGISDialogBase")
        WtyczkaQGISDialogBase.resize(1124, 648)
        self.pushButton_calculate_deltaH = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_calculate_deltaH.setGeometry(QtCore.QRect(320, 130, 191, 51))
        self.pushButton_calculate_deltaH.setObjectName("pushButton_calculate_deltaH")
        self.label_mapDescription = QtWidgets.QLabel(WtyczkaQGISDialogBase)
        self.label_mapDescription.setGeometry(QtCore.QRect(330, 30, 211, 51))
        self.label_mapDescription.setObjectName("label_mapDescription")
        self.label_3_result = QtWidgets.QLabel(WtyczkaQGISDialogBase)
        self.label_3_result.setGeometry(QtCore.QRect(250, 440, 741, 51))
        self.label_3_result.setText("")
        self.label_3_result.setObjectName("label_3_result")
        self.mMapLayerComboBox = QgsMapLayerComboBox(WtyczkaQGISDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(460, 40, 160, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label_2_result_description = QtWidgets.QLabel(WtyczkaQGISDialogBase)
        self.label_2_result_description.setGeometry(QtCore.QRect(190, 440, 161, 51))
        self.label_2_result_description.setObjectName("label_2_result_description")
        self.pushButton_calculate_pole = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_calculate_pole.setGeometry(QtCore.QRect(530, 130, 191, 51))
        self.pushButton_calculate_pole.setObjectName("pushButton_calculate_pole")
        self.pushButton_calculate_pole_m2 = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_calculate_pole_m2.setGeometry(QtCore.QRect(590, 180, 131, 51))
        self.pushButton_calculate_pole_m2.setObjectName("pushButton_calculate_pole_m2")
        self.pushButton_calculate_pole_ar = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_calculate_pole_ar.setGeometry(QtCore.QRect(660, 230, 61, 51))
        self.pushButton_calculate_pole_ar.setObjectName("pushButton_calculate_pole_ar")
        self.pushButton_calculate_pole_ha = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_calculate_pole_ha.setGeometry(QtCore.QRect(640, 280, 81, 51))
        self.pushButton_calculate_pole_ha.setObjectName("pushButton_calculate_pole_ha")
        self.label_2_result_points_description = QtWidgets.QLabel(WtyczkaQGISDialogBase)
        self.label_2_result_points_description.setGeometry(QtCore.QRect(190, 350, 161, 51))
        self.label_2_result_points_description.setObjectName("label_2_result_points_description")
        self.label_3_result_2 = QtWidgets.QLabel(WtyczkaQGISDialogBase)
        self.label_3_result_2.setGeometry(QtCore.QRect(300, 350, 741, 51))
        self.label_3_result_2.setText("")
        self.label_3_result_2.setObjectName("label_3_result_2")
        self.pushButton_clear = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_clear.setGeometry(QtCore.QRect(630, 530, 93, 28))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_close = QtWidgets.QPushButton(WtyczkaQGISDialogBase)
        self.pushButton_close.setGeometry(QtCore.QRect(730, 530, 93, 28))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(WtyczkaQGISDialogBase)
        QtCore.QMetaObject.connectSlotsByName(WtyczkaQGISDialogBase)

    def retranslateUi(self, WtyczkaQGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaQGISDialogBase.setWindowTitle(_translate("WtyczkaQGISDialogBase", "Wtyczka"))
        self.pushButton_calculate_deltaH.setText(_translate("WtyczkaQGISDialogBase", "oblicz przewyższenie"))
        self.label_mapDescription.setText(_translate("WtyczkaQGISDialogBase", "Wybierz warstwę"))
        self.label_2_result_description.setText(_translate("WtyczkaQGISDialogBase", "Wynik:"))
        self.pushButton_calculate_pole.setText(_translate("WtyczkaQGISDialogBase", "oblicz pole powierzchni"))
        self.pushButton_calculate_pole_m2.setText(_translate("WtyczkaQGISDialogBase", "metry kwadratowe"))
        self.pushButton_calculate_pole_ar.setText(_translate("WtyczkaQGISDialogBase", "ary"))
        self.pushButton_calculate_pole_ha.setText(_translate("WtyczkaQGISDialogBase", "hektary"))
        self.label_2_result_points_description.setText(_translate("WtyczkaQGISDialogBase", "Wybrane punkty:"))
        self.pushButton_clear.setText(_translate("WtyczkaQGISDialogBase", "Wyczyść"))
        self.pushButton_close.setText(_translate("WtyczkaQGISDialogBase", "Zamknij"))
from qgsmaplayercombobox import QgsMapLayerComboBox
